package com.bt.shopguide.dao.mapper;

import com.bt.shopguide.dao.entity.GoodCheap;

public interface GoodCheapMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOOD_CHEAPS
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOOD_CHEAPS
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    int insert(GoodCheap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOOD_CHEAPS
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    int insertSelective(GoodCheap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOOD_CHEAPS
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    GoodCheap selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOOD_CHEAPS
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    int updateByPrimaryKeySelective(GoodCheap record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOOD_CHEAPS
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    int updateByPrimaryKey(GoodCheap record);
}