package com.bt.shopguide.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class GoodCheap implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOOD_CHEAPS.id
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOOD_CHEAPS.title
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOOD_CHEAPS.list_image
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    private String listImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOOD_CHEAPS.price
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOOD_CHEAPS.coupon
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    private String coupon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOOD_CHEAPS.url
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOOD_CHEAPS.category
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOOD_CHEAPS.publish
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    private Byte publish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOOD_CHEAPS.sync_time
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    private Date syncTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOOD_CHEAPS.create_time
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOOD_CHEAPS.id
     *
     * @return the value of GOOD_CHEAPS.id
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOOD_CHEAPS.id
     *
     * @param id the value for GOOD_CHEAPS.id
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOOD_CHEAPS.title
     *
     * @return the value of GOOD_CHEAPS.title
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOOD_CHEAPS.title
     *
     * @param title the value for GOOD_CHEAPS.title
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOOD_CHEAPS.list_image
     *
     * @return the value of GOOD_CHEAPS.list_image
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    public String getListImage() {
        return listImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOOD_CHEAPS.list_image
     *
     * @param listImage the value for GOOD_CHEAPS.list_image
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    public void setListImage(String listImage) {
        this.listImage = listImage == null ? null : listImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOOD_CHEAPS.price
     *
     * @return the value of GOOD_CHEAPS.price
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOOD_CHEAPS.price
     *
     * @param price the value for GOOD_CHEAPS.price
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOOD_CHEAPS.coupon
     *
     * @return the value of GOOD_CHEAPS.coupon
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    public String getCoupon() {
        return coupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOOD_CHEAPS.coupon
     *
     * @param coupon the value for GOOD_CHEAPS.coupon
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    public void setCoupon(String coupon) {
        this.coupon = coupon == null ? null : coupon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOOD_CHEAPS.url
     *
     * @return the value of GOOD_CHEAPS.url
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOOD_CHEAPS.url
     *
     * @param url the value for GOOD_CHEAPS.url
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOOD_CHEAPS.category
     *
     * @return the value of GOOD_CHEAPS.category
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOOD_CHEAPS.category
     *
     * @param category the value for GOOD_CHEAPS.category
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOOD_CHEAPS.publish
     *
     * @return the value of GOOD_CHEAPS.publish
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    public Byte getPublish() {
        return publish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOOD_CHEAPS.publish
     *
     * @param publish the value for GOOD_CHEAPS.publish
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    public void setPublish(Byte publish) {
        this.publish = publish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOOD_CHEAPS.sync_time
     *
     * @return the value of GOOD_CHEAPS.sync_time
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    public Date getSyncTime() {
        return syncTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOOD_CHEAPS.sync_time
     *
     * @param syncTime the value for GOOD_CHEAPS.sync_time
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    public void setSyncTime(Date syncTime) {
        this.syncTime = syncTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOOD_CHEAPS.create_time
     *
     * @return the value of GOOD_CHEAPS.create_time
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOOD_CHEAPS.create_time
     *
     * @param createTime the value for GOOD_CHEAPS.create_time
     *
     * @mbggenerated Fri Dec 29 11:22:24 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}